# Generated by Django 4.2.27 on 2025-12-11 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='services',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicetype'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='duration',
            field=models.IntegerField(default=30, verbose_name='Duração (minutos)'),
        ),
    ]
